name: flutter-desktop-picture-taker
version: '1.0'
summary: Desktop Counter App
description: Super Cool Counter App.
confinement: strict
base: core18
grade: stable

apps:
  flutter-desktop-sample:
    command: flutter_desktop_sample_picture_taker
    extensions: [flutter-master]

parts:
  flutter-desktop-sample:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart

